apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recipe-rescue-postgres-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: recipe-rescue-aws-secrets
    kind: ClusterSecretStore
  target:
    name: recipe-rescue-postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: recipe-rescue/production/app
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: recipe-rescue/production/app
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: recipe-rescue/production/app
        property: POSTGRES_PASSWORD
