apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: recipe-rescue
  namespace: argocd
spec:
  description: Recipe Rescue GitOps project
  sourceRepos:
    - {{ .Values.repoUrl | quote }}
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: recipe-rescue-staging
      server: https://kubernetes.default.svc
    - namespace: recipe-rescue-production-data
      server: https://kubernetes.default.svc
    - namespace: recipe-rescue-production
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
