apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recipe-rescue-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: recipe-rescue-aws-secrets
    kind: ClusterSecretStore
  target:
    name: recipe-rescue-repo
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: "{{ `{{ .repoType }}` }}"
        url: "{{ `{{ .repoUrl }}` }}"
        username: "{{ `{{ .repoUsername }}` }}"
        password: "{{ `{{ .repoPassword }}` }}"
  data:
    - secretKey: repoType
      remoteRef:
        key: {{ .Values.argocdGithubRepoSecret | quote }}
        property: type
    - secretKey: repoUrl
      remoteRef:
        key: {{ .Values.argocdGithubRepoSecret | quote }}
        property: url
    - secretKey: repoUsername
      remoteRef:
        key: {{ .Values.argocdGithubRepoSecret | quote }}
        property: username
    - secretKey: repoPassword
      remoteRef:
        key: {{ .Values.argocdGithubRepoSecret | quote }}
        property: password
