apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: recipe-rescue-aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion | quote }}
