apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: recipe-rescue-green
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: recipe-rescue
      app.kubernetes.io/environment: production
      app.kubernetes.io/deployment-color: green
patches:
  - target:
      kind: Namespace
      name: recipe-rescue
    patch: |-
      - op: replace
        path: /metadata/name
        value: recipe-rescue-green
  - target:
      kind: ConfigMap
      name: recipe-rescue-config
    patch: |-
      - op: replace
        path: /data/ALLOWED_ORIGINS
        value: '["https://green.recipe-rescue.local"]'
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: recipe-rescue-postgres
        namespace: recipe-rescue
      $patch: delete
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: recipe-rescue-postgres
        namespace: recipe-rescue
      $patch: delete
