apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipe-rescue-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: recipe-rescue
  source:
    repoURL: https://github.com/iulianradean98/final_project.git
    targetRevision: staging
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: recipe-rescue-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
