apiVersion: v1
kind: Service
metadata:
  name: recipe-rescue-router
  labels:
    app.kubernetes.io/name: recipe-rescue-router
    app.kubernetes.io/component: edge-router
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: recipe-rescue-router
    app.kubernetes.io/component: edge-router
