apiVersion: v1
kind: Service
metadata:
  name: recipe-rescue-api
  namespace: recipe-rescue
  labels:
    app.kubernetes.io/name: recipe-rescue-api
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app.kubernetes.io/name: recipe-rescue-api
    app.kubernetes.io/component: backend
