apiVersion: v1
kind: ServiceAccount
metadata:
  name: recipe-rescue-db-backup
  namespace: recipe-rescue
  labels:
    app.kubernetes.io/name: recipe-rescue-db-backup
    app.kubernetes.io/component: database-backup
