name: Release Checks

on:
  pull_request:
    branches:
      - release
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  release-changed-files:
    name: Release changed files
    uses: ./.github/workflows/check-release-changed-files.yml

  release-image-tags:
    name: Release image tags
    uses: ./.github/workflows/check-release-image-tags.yml

  release-images-exist:
    name: Release Docker images exist
    uses: ./.github/workflows/check-release-images-exist.yml

  release-overlay-render:
    name: Release overlay render
    uses: ./.github/workflows/check-release-overlay-render.yml
