apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - api-external-secret.yaml
  - postgres-external-secret.yaml
namespace: recipe-rescue-staging
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: recipe-rescue
      app.kubernetes.io/environment: staging
patches:
  - target:
      kind: Namespace
      name: recipe-rescue
    patch: |-
      - op: replace
        path: /metadata/name
        value: recipe-rescue-staging
  - target:
      kind: ConfigMap
      name: recipe-rescue-config
    patch: |-
      - op: replace
        path: /data/ALLOWED_ORIGINS
        value: '["http://localhost:3001","http://recipe-rescue-staging.local"]'
images:
  - name: iulian98/recipe-rescue-backend
    newTag: sha-507dfef31033
  - name: iulian98/recipe-rescue-frontend
    newTag: sha-507dfef31033
